wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-regular.eot
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-regular.eot?#iefix
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-regular.woff
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-regular.ttf
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bold.eot
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bold.eot?#iefix
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bold.woff
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bold.ttf
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-italic.eot
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-italic.eot?#iefix
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-italic.woff
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-italic.ttf
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bolditalic.eot
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bolditalic.eot?#iefix
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bolditalic.woff
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans-bolditalic.ttf