wget https://s3.amazonaws.com/static.slid.es/fonts/montserrat/montserrat.css
wget https://s3.amazonaws.com/static.slid.es/fonts/opensans/opensans.css
wget https://s3.amazonaws.com/static.slid.es/fonts/lato/lato.css
wget https://s3.amazonaws.com/static.slid.es/fonts/asul/asul.css
wget https://s3.amazonaws.com/static.slid.es/fonts/josefinsans/josefinsans.css
wget https://s3.amazonaws.com/static.slid.es/fonts/league/league_gothic.css
wget https://s3.amazonaws.com/static.slid.es/fonts/merriweathersans/merriweathersans.css
wget https://s3.amazonaws.com/static.slid.es/fonts/overpass/overpass.css
wget https://s3.amazonaws.com/static.slid.es/fonts/quicksand/quicksand.css
wget https://s3.amazonaws.com/static.slid.es/fonts/cabinsketch/cabinsketch.css
wget https://s3.amazonaws.com/static.slid.es/fonts/newscycle/newscycle.css
wget https://s3.amazonaws.com/static.slid.es/fonts/oxygen/oxygen.css